name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AUTHOR }}

    - name: Test SSH connection
      run: |
       run: ssh -o StrictHostKeyChecking=no -T ${{ secrets.UBUNTU_USER }}@${{ secrets.UBUNTU_HOST }} "uptime && whoami"

    
    - name: Copy files to EC2
      run: |
        run: ssh -o StrictHostKeyChecking=no -T ${{ secrets.UBUNTU_USER}}@${{ UBUNTU_HOST }}:~/myapp/
  

    - name: Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.UBUNTU_USER }}@${{ secrets.UBUNTU_HOST }} << 'EOF'
        cd ~/myapp
        sudo docker-compose down
        sudo docker-compose up -d --build
        EOF
